/**
* This file is autogenerated by nRFgo Studio 1.17.1.3252
*/

#include "services.h"
#include "lib_aci.h"

static bool is_nordic_uart_over_btle_uart_tx_send_requested = false;

static void *nordic_uart_over_btle_uart_tx_tx;
static uint8_t nordic_uart_over_btle_uart_tx_tx_size;

static bool nordic_uart_over_btle_uart_tx_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_NORDIC_UART_OVER_BTLE_UART_TX_TX))
  {
    return(lib_aci_send_data(PIPE_NORDIC_UART_OVER_BTLE_UART_TX_TX, (void*)nordic_uart_over_btle_uart_tx_tx, nordic_uart_over_btle_uart_tx_tx_size));
  }
  return(false);
}

bool services_send_nordic_uart_over_btle_uart_tx(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_nordic_uart_over_btle_uart_tx_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_nordic_uart_over_btle_uart_tx_send_requested)
    {
      nordic_uart_over_btle_uart_tx_tx_size = size;
      nordic_uart_over_btle_uart_tx_tx = src;
      is_nordic_uart_over_btle_uart_tx_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    nordic_uart_over_btle_uart_tx_tx_size = size;
    nordic_uart_over_btle_uart_tx_tx = src;
    is_nordic_uart_over_btle_uart_tx_send_requested = true;
    services_update_pipes();
    return(true);
  }
}

void services_update_pipes(void)
{
  if(is_nordic_uart_over_btle_uart_tx_send_requested)
  {
    is_nordic_uart_over_btle_uart_tx_send_requested = !(nordic_uart_over_btle_uart_tx_update_send());
  }
}

